apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: python-application
  name: python-application
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 5000
  selector:
    io.kompose.service: python-application
status:
  loadBalancer: {}
