apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: python-application
  name: python-application
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: python-application
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/prometheus-default: "true"
        io.kompose.service: python-application
    spec:
      containers:
        - image: gouravsingh29/python-application
          name: python-application
          ports:
            - containerPort: 5000
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
